CREATE DATABASE IF NOT EXISTS client_system;
USE client_system;

CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  companyName VARCHAR(255),
  bdMemberName VARCHAR(255),
  dateClientAcquired DATE,
  address TEXT,
  city VARCHAR(100),
  pinCode VARCHAR(20),
  locationArea VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100),
  yearOfEstablishment VARCHAR(10),
  industry VARCHAR(100),
  subIndustry VARCHAR(100),
  tags VARCHAR(255),
  companyConstitution VARCHAR(100),
  numberOfEmployees VARCHAR(50),
  gstNo VARCHAR(20),
  website VARCHAR(255),
  contactPersonName VARCHAR(255),
  designation VARCHAR(100),
  phoneNumber VARCHAR(20),
  emailId VARCHAR(255),
  contactPersonStatus VARCHAR(50) DEFAULT 'Active',
  placementFees DECIMAL(10,2),
  additionalPlacementFees VARCHAR(10) DEFAULT 'No',
  creditPeriod VARCHAR(20),
  replacementPeriod VARCHAR(20),
  companyCategory VARCHAR(10),
  companyStatus VARCHAR(50),
  approvalStatus VARCHAR(50),
  remarks TEXT,
  dateOfRevivalCall DATE,
  nameOfExecutive VARCHAR(255),
  statusOfCall VARCHAR(50),
  eMeet VARCHAR(10) DEFAULT 'No',
  updated VARCHAR(10) DEFAULT 'No',
  dateOfDataUpdate DATE,
  dataUpdatedBy VARCHAR(255),
  teamLeader VARCHAR(255),
  franchiseeName VARCHAR(255),
  dateOfClientAllocation DATE,
  reallocationStatus VARCHAR(10) DEFAULT 'No',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);